
services:
  streamlit:
    build: ./streamlit_app
    container_name: streamlit
    restart: always
    ports:
      - "8501:8501"
    devices:
      - /dev/video0:/dev/video0
      - /dev/video1:/dev/video1
    privileged: true
    environment:
      - STREAMLIT_SERVER_PORT=8501
    group_add:
      - video

